version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    environment:
      APP_NAME: ${APP_NAME}
      HTTP_PORT: ${HTTP_PORT}
      TARGET_SITE: ${TARGET_SITE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:4
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?sslmode=disable", "up"]
    depends_on:
      - postgres


volumes:
  postgres_data: {}
