name: "Test and Deploy"
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.22.0'

      - name: Test application
        run: |
          make test

  deploy:
    runs-on: ubuntu-22.04
    needs: test
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    env:
      APP_DIR: bazacars
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.22.0'

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_APP_NAME: "Bazacars"
          envkey_APP_VERSION: ${{ github.ref_name }}
          envkey_TARGET_SITE: ${{ secrets.TARGET_SITE }}
          envkey_TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          envkey_POSTGRES_HOST: postgres
          envkey_POSTGRES_DB: bazacars
          envkey_POSTGRES_PORT: 5445
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_HTTP_PORT: 8124

      - name: Build application
        run: |
          make build

      - name: Stop application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.APP_DIR }}
            docker-compose down || true

      - name: Deploy application
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "migrations/,app,.env,Dockerfile,docker-compose.yml"
          target: /home/${{ secrets.USER }}/${{ env.APP_DIR }}
          rm: true
          args: -r

      - name: Start application
        uses: appleboy/ssh-action@v0.1.10
        if: always()
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.APP_DIR }}              
            docker-compose up --build -d
